"""Profile raw Olist CSV datasets and generate docs/data_dictionary.md and validation checks."""

from pathlib import Path
import pandas as pd
from src.config import DATA_RAW, DOCS_DIR


# Define expected grain and key definition for each table
TABLE_CONFIG = {
    "olist_customers_dataset.csv": {
        "table_name": "raw_customers",
        "grain": "One row per customer account / order session identity (customer_id)",
        "primary_key": ["customer_id"],
        "notes": "customer_unique_id represents the real person across multiple orders.",
    },
    "olist_orders_dataset.csv": {
        "table_name": "raw_orders",
        "grain": "One row per customer order",
        "primary_key": ["order_id"],
        "notes": "Links to raw_customers via customer_id. Contains order lifecycle timestamps.",
    },
    "olist_order_items_dataset.csv": {
        "table_name": "raw_order_items",
        "grain": "One row per item in an order",
        "primary_key": ["order_id", "order_item_id"],
        "notes": "order_item_id is sequential 1..N per order. Links to raw_products and raw_sellers.",
    },
    "olist_order_payments_dataset.csv": {
        "table_name": "raw_order_payments",
        "grain": "One row per payment installment/method sequence within an order",
        "primary_key": ["order_id", "payment_sequential"],
        "notes": "An order can have multiple sequential payment installments/vouchers.",
    },
    "olist_order_reviews_dataset.csv": {
        "table_name": "raw_order_reviews",
        "grain": "One row per review record (or review submission per order)",
        "primary_key": ["review_id", "order_id"],
        "notes": "review_id can have duplicate rows if a review applies to multiple orders or surveys.",
    },
    "olist_products_dataset.csv": {
        "table_name": "raw_products",
        "grain": "One row per product catalog entry",
        "primary_key": ["product_id"],
        "notes": "Product specifications and Portuguese category name.",
    },
    "olist_sellers_dataset.csv": {
        "table_name": "raw_sellers",
        "grain": "One row per seller merchant account",
        "primary_key": ["seller_id"],
        "notes": "Seller merchant zip code prefix, city, and state.",
    },
    "olist_geolocation_dataset.csv": {
        "table_name": "raw_geolocation",
        "grain": "Multiple coordinates per zip code prefix / city / state",
        "primary_key": None,
        "notes": "Contains many coordinate samples per geolocation_zip_code_prefix. No unique row ID.",
    },
    "product_category_name_translation.csv": {
        "table_name": "raw_category_translation",
        "grain": "One row per Portuguese category name translation",
        "primary_key": ["product_category_name"],
        "notes": "Maps Portuguese category name to English category name.",
    },
}


def profile_datasets() -> dict:
    """Read all CSVs in DATA_RAW, compute schema, row counts, null rates, and key uniqueness."""
    results = {}

    for csv_file, meta in TABLE_CONFIG.items():
        file_path = DATA_RAW / csv_file
        if not file_path.exists():
            continue

        df = pd.read_csv(file_path)
        row_count = len(df)
        col_count = len(df.columns)

        # Profile columns
        col_profiles = []
        for col in df.columns:
            null_count = int(df[col].isna().sum())
            null_pct = (null_count / row_count * 100.0) if row_count > 0 else 0.0
            n_unique = int(df[col].nunique(dropna=True))
            dtype = str(df[col].dtype)
            sample_val = str(df[col].dropna().iloc[0]) if not df[col].dropna().empty else "None"
            col_profiles.append(
                {
                    "column": col,
                    "dtype": dtype,
                    "null_count": null_count,
                    "null_pct": round(null_pct, 2),
                    "unique_values": n_unique,
                    "sample": sample_val[:50],
                }
            )

        # Key uniqueness check
        pk = meta["primary_key"]
        is_pk_unique = None
        pk_duplicates = 0
        if pk is not None:
            dups = df.duplicated(subset=pk, keep=False)
            pk_duplicates = int(dups.sum())
            is_pk_unique = pk_duplicates == 0

        results[csv_file] = {
            "meta": meta,
            "row_count": row_count,
            "col_count": col_count,
            "columns": col_profiles,
            "is_pk_unique": is_pk_unique,
            "pk_duplicates": pk_duplicates,
        }

    return results


def generate_data_dictionary(profile_results: dict, output_file: Path) -> None:
    """Format profiled results into docs/data_dictionary.md."""
    lines = [
        "# Olist Brazilian E-Commerce Data Dictionary",
        "",
        "Auto-generated by `src/profile_data.py`. Summarizes table grains, row counts, keys, data types, null rates, and field notes.",
        "",
    ]

    for csv_file, res in profile_results.items():
        meta = res["meta"]
        lines.append(f"## {csv_file} (`{meta['table_name']}`)")
        lines.append(f"- **Grain**: {meta['grain']}")
        lines.append(f"- **Total Rows**: {res['row_count']:,}")
        lines.append(f"- **Columns**: {res['col_count']}")
        pk_display = ", ".join(meta["primary_key"]) if meta["primary_key"] else "None (Composite/Dimension)"
        lines.append(f"- **Candidate Key(s)**: `{pk_display}`")
        if meta["primary_key"] is not None:
            status_str = "✅ YES" if res["is_pk_unique"] else f"❌ NO ({res['pk_duplicates']} duplicates)"
            lines.append(f"- **Key Unique**: {status_str}")
        lines.append(f"- **Notes**: {meta['notes']}")
        lines.append("")
        lines.append("| Column | Data Type | Null Count | Null % | Unique Values | Sample Value |")
        lines.append("| :--- | :--- | :--- | :--- | :--- | :--- |")
        for col in res["columns"]:
            lines.append(
                f"| `{col['column']}` | {col['dtype']} | {col['null_count']:,} | {col['null_pct']:.2f}% | {col['unique_values']:,} | `{col['sample']}` |"
            )
        lines.append("")

    output_file.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    profiles = profile_datasets()
    dict_path = DOCS_DIR / "data_dictionary.md"
    generate_data_dictionary(profiles, dict_path)
    print(f"Data dictionary generated successfully at {dict_path}")
    for fname, data in profiles.items():
        pk = data["meta"]["primary_key"]
        pk_str = ", ".join(pk) if pk else "None"
        uniq = data["is_pk_unique"]
        print(f"  - {fname}: {data['row_count']} rows, PK [{pk_str}] Unique={uniq}")
